"""add hotel tables

Revision ID: 0449ad751e77
Revises: 2297a13327c9
Create Date: 2026-03-20 14:40:19.477736

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0449ad751e77'
down_revision: Union[str, None] = '2297a13327c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('hotel_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_from_temple', sa.Float(), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('check_in_time', sa.String(length=10), nullable=False),
    sa.Column('check_out_time', sa.String(length=10), nullable=False),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('pet_policy', sa.String(length=20), nullable=False),
    sa.Column('meal_options', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_partner_id'), 'hotels', ['partner_id'], unique=False)
    op.create_table('hotel_amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_amenities_hotel_id'), 'hotel_amenities', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_amenities_id'), 'hotel_amenities', ['id'], unique=False)
    op.create_table('hotel_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_images_hotel_id'), 'hotel_images', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_images_id'), 'hotel_images', ['id'], unique=False)
    op.create_table('hotel_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weekend_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_bed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bed_type', sa.String(length=30), nullable=True),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_tv', sa.Boolean(), nullable=False),
    sa.Column('has_geyser', sa.Boolean(), nullable=False),
    sa.Column('is_smoking', sa.Boolean(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_rooms_hotel_id'), 'hotel_rooms', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_rooms_id'), 'hotel_rooms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_rooms_id'), table_name='hotel_rooms')
    op.drop_index(op.f('ix_hotel_rooms_hotel_id'), table_name='hotel_rooms')
    op.drop_table('hotel_rooms')
    op.drop_index(op.f('ix_hotel_images_id'), table_name='hotel_images')
    op.drop_index(op.f('ix_hotel_images_hotel_id'), table_name='hotel_images')
    op.drop_table('hotel_images')
    op.drop_index(op.f('ix_hotel_amenities_id'), table_name='hotel_amenities')
    op.drop_index(op.f('ix_hotel_amenities_hotel_id'), table_name='hotel_amenities')
    op.drop_table('hotel_amenities')
    op.drop_index(op.f('ix_hotels_partner_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
