"""fix duplicate tables

Revision ID: 0452a0f92a7e
Revises: de7b01f846d0
Create Date: 2026-03-23 14:00:21.545181

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0452a0f92a7e'
down_revision: Union[str, None] = 'de7b01f846d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_type', sa.Enum('VEHICLE', 'HOTEL', 'PACKAGE', 'DARSHAN', name='bookingtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('booking_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('custom_trip_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_number')
    )
    op.create_index('ix_bookings_payment_status', 'bookings', ['payment_status'], unique=False)
    op.create_index('ix_bookings_user_dates', 'bookings', ['user_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_bookings_user_status', 'bookings', ['user_id', 'status'], unique=False)
    op.create_index('ix_bookings_user_type', 'bookings', ['user_id', 'booking_type'], unique=False)
    op.create_table('booking_addons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('addon_type', sa.String(length=50), nullable=False),
    sa.Column('addon_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_addons_booking_id'), 'booking_addons', ['booking_id'], unique=False)
    op.create_table('booking_travelers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('id_proof_type', sa.String(length=50), nullable=True),
    sa.Column('id_proof_number', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_travelers_booking_id'), 'booking_travelers', ['booking_id'], unique=False)
    op.create_table('guide_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('num_hours', sa.Integer(), nullable=True),
    sa.Column('num_days', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meeting_point', sa.String(length=500), nullable=True),
    sa.Column('locations_to_cover', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_bookings_booking_id'), 'guide_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_guide_bookings_guide_id'), 'guide_bookings', ['guide_id'], unique=False)
    op.create_table('hotel_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('room_rate_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_room_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('guest_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_bookings_booking_id'), 'hotel_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_hotel_bookings_hotel_id'), 'hotel_bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_bookings_room_id'), 'hotel_bookings', ['room_id'], unique=False)
    op.create_table('package_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('num_adults', sa.Integer(), nullable=False),
    sa.Column('num_children', sa.Integer(), nullable=False),
    sa.Column('package_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('addon_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customizations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_bookings_booking_id'), 'package_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_package_bookings_package_id'), 'package_bookings', ['package_id'], unique=False)
    op.create_table('vehicle_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('trip_type', sa.Enum('ONE_WAY', 'ROUND_TRIP', name='triptype'), nullable=False),
    sa.Column('pickup_location', sa.String(length=500), nullable=False),
    sa.Column('pickup_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('pickup_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('drop_location', sa.String(length=500), nullable=False),
    sa.Column('drop_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('drop_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_per_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('toll_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('route_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_bookings_booking_id'), 'vehicle_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_vehicle_bookings_driver_id'), 'vehicle_bookings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_bookings_vehicle_id'), 'vehicle_bookings', ['vehicle_id'], unique=False)
    op.add_column('darshan_bookings', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.add_column('darshan_bookings', sa.Column('darshan_slot_id', sa.UUID(), nullable=False))
    op.add_column('darshan_bookings', sa.Column('darshan_type_id', sa.UUID(), nullable=False))
    op.add_column('darshan_bookings', sa.Column('darshan_date', sa.Date(), nullable=False))
    op.add_column('darshan_bookings', sa.Column('darshan_time', sa.Time(), nullable=False))
    op.add_column('darshan_bookings', sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('darshan_bookings', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('darshan_bookings', sa.Column('devotee_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('darshan_bookings', sa.Column('ticket_number', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_darshan_bookings_booking_reference'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_slot_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_user_id'), table_name='darshan_bookings')
    op.create_index(op.f('ix_darshan_bookings_booking_id'), 'darshan_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_darshan_bookings_darshan_slot_id'), 'darshan_bookings', ['darshan_slot_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_darshan_type_id'), 'darshan_bookings', ['darshan_type_id'], unique=False)
    op.create_unique_constraint(None, 'darshan_bookings', ['ticket_number'])
    op.drop_constraint(op.f('darshan_bookings_temple_id_fkey'), 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(op.f('darshan_bookings_slot_id_fkey'), 'darshan_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'darshan_bookings', 'bookings', ['booking_id'], ['id'])
    op.drop_column('darshan_bookings', 'updated_at')
    op.drop_column('darshan_bookings', 'pilgrim_details')
    op.drop_column('darshan_bookings', 'booking_reference')
    op.drop_column('darshan_bookings', 'qr_code')
    op.drop_column('darshan_bookings', 'slot_id')
    op.drop_column('darshan_bookings', 'status')
    op.drop_column('darshan_bookings', 'payment_id')
    op.drop_column('darshan_bookings', 'created_at')
    op.drop_column('darshan_bookings', 'user_id')
    op.drop_column('darshan_bookings', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('darshan_bookings', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('darshan_bookings', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('darshan_bookings', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('darshan_bookings', sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('darshan_bookings', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('darshan_bookings', sa.Column('slot_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('darshan_bookings', sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('darshan_bookings', sa.Column('booking_reference', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('darshan_bookings', sa.Column('pilgrim_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('darshan_bookings', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.create_foreign_key(op.f('darshan_bookings_slot_id_fkey'), 'darshan_bookings', 'darshan_slots', ['slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('darshan_bookings_temple_id_fkey'), 'darshan_bookings', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'darshan_bookings', type_='unique')
    op.drop_index(op.f('ix_darshan_bookings_darshan_type_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_darshan_slot_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_booking_id'), table_name='darshan_bookings')
    op.create_index(op.f('ix_darshan_bookings_user_id'), 'darshan_bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_slot_id'), 'darshan_bookings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_booking_reference'), 'darshan_bookings', ['booking_reference'], unique=True)
    op.drop_column('darshan_bookings', 'ticket_number')
    op.drop_column('darshan_bookings', 'devotee_details')
    op.drop_column('darshan_bookings', 'total_price')
    op.drop_column('darshan_bookings', 'price_per_person')
    op.drop_column('darshan_bookings', 'darshan_time')
    op.drop_column('darshan_bookings', 'darshan_date')
    op.drop_column('darshan_bookings', 'darshan_type_id')
    op.drop_column('darshan_bookings', 'darshan_slot_id')
    op.drop_column('darshan_bookings', 'booking_id')
    op.drop_index(op.f('ix_vehicle_bookings_vehicle_id'), table_name='vehicle_bookings')
    op.drop_index(op.f('ix_vehicle_bookings_driver_id'), table_name='vehicle_bookings')
    op.drop_index(op.f('ix_vehicle_bookings_booking_id'), table_name='vehicle_bookings')
    op.drop_table('vehicle_bookings')
    op.drop_index(op.f('ix_package_bookings_package_id'), table_name='package_bookings')
    op.drop_index(op.f('ix_package_bookings_booking_id'), table_name='package_bookings')
    op.drop_table('package_bookings')
    op.drop_index(op.f('ix_hotel_bookings_room_id'), table_name='hotel_bookings')
    op.drop_index(op.f('ix_hotel_bookings_hotel_id'), table_name='hotel_bookings')
    op.drop_index(op.f('ix_hotel_bookings_booking_id'), table_name='hotel_bookings')
    op.drop_table('hotel_bookings')
    op.drop_index(op.f('ix_guide_bookings_guide_id'), table_name='guide_bookings')
    op.drop_index(op.f('ix_guide_bookings_booking_id'), table_name='guide_bookings')
    op.drop_table('guide_bookings')
    op.drop_index(op.f('ix_booking_travelers_booking_id'), table_name='booking_travelers')
    op.drop_table('booking_travelers')
    op.drop_index(op.f('ix_booking_addons_booking_id'), table_name='booking_addons')
    op.drop_table('booking_addons')
    op.drop_index('ix_bookings_user_type', table_name='bookings')
    op.drop_index('ix_bookings_user_status', table_name='bookings')
    op.drop_index('ix_bookings_user_dates', table_name='bookings')
    op.drop_index('ix_bookings_payment_status', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
