"""add_indexes_to_wallet_tables

Revision ID: 0a9b5f4b434f
Revises: 8281310bd86a
Create Date: 2026-03-24 16:20:14.326035

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0a9b5f4b434f'
down_revision: Union[str, None] = '8281310bd86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.drop_constraint(op.f('wallets_user_id_key'), 'wallets', type_='unique')
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_index(op.f('ix_withdrawal_requests_id'), 'withdrawal_requests', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_wallet_id'), 'withdrawal_requests', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_requests_wallet_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.create_unique_constraint(op.f('wallets_user_id_key'), 'wallets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.alter_column('tracking_sessions', 'tracker_role',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='trackingsessionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
