"""booking tables

Revision ID: 0df9f7fc524c
Revises: 2ab3eefe8be4
Create Date: 2026-03-23 21:32:06.972963

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0df9f7fc524c'
down_revision: Union[str, None] = '2ab3eefe8be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=True)
    op.drop_constraint(op.f('bookings_booking_number_key'), 'bookings', type_='unique')
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookings', 'end_date')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'start_date')
    op.drop_column('bookings', 'contact_details')
    op.drop_column('bookings', 'completed_at')
    op.drop_column('bookings', 'convenience_fee')
    op.drop_column('bookings', 'coupon_code')
    op.drop_column('bookings', 'tax_amount')
    op.drop_column('bookings', 'special_requests')
    op.drop_column('bookings', 'booking_number')
    op.drop_column('bookings', 'custom_trip_details')
    op.drop_column('bookings', 'cancellation_reason')
    op.drop_column('bookings', 'booking_date')
    op.drop_column('bookings', 'discount_amount')
    op.drop_column('bookings', 'confirmed_at')
    op.drop_column('bookings', 'paid_amount')
    op.drop_column('bookings', 'subtotal')
    op.alter_column('darshan_bookings', 'darshan_slot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('darshan_bookings', 'darshan_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('darshan_bookings', 'devotee_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_darshan_bookings_booking_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_temple_id'), table_name='darshan_bookings')
    op.create_unique_constraint(None, 'darshan_bookings', ['booking_id'])
    op.drop_constraint(op.f('darshan_bookings_temple_id_fkey'), 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(op.f('darshan_bookings_darshan_slot_id_fkey'), 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(op.f('darshan_bookings_darshan_type_id_fkey'), 'darshan_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'darshan_bookings', 'darshan_slots', ['darshan_slot_id'], ['id'])
    op.create_foreign_key(None, 'darshan_bookings', 'darshan_types', ['darshan_type_id'], ['id'])
    op.create_foreign_key(None, 'darshan_bookings', 'temples', ['temple_id'], ['id'])
    op.alter_column('darshan_slots', 'booked_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('darshan_slots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('darshan_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('darshan_slots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_darshan_slots_darshan_type_id'), table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_slots_slot_date'), table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_slots_temple_id'), table_name='darshan_slots')
    op.drop_constraint(op.f('darshan_slots_temple_id_fkey'), 'darshan_slots', type_='foreignkey')
    op.drop_constraint(op.f('darshan_slots_darshan_type_id_fkey'), 'darshan_slots', type_='foreignkey')
    op.create_foreign_key(None, 'darshan_slots', 'temples', ['temple_id'], ['id'])
    op.create_foreign_key(None, 'darshan_slots', 'darshan_types', ['darshan_type_id'], ['id'])
    op.alter_column('darshan_types', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('darshan_types', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('darshan_types', 'max_persons_per_booking',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('darshan_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('darshan_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('darshan_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pooja_bookings', 'temple_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pooja_bookings', 'pooja_service_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pooja_bookings', 'booking_reference',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('pooja_bookings', 'num_persons',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pooja_bookings', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pooja_bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('pooja_bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pooja_bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_pooja_bookings_booking_id'), table_name='pooja_bookings')
    op.drop_index(op.f('ix_pooja_bookings_temple_id'), table_name='pooja_bookings')
    op.drop_index(op.f('ix_pooja_bookings_user_id'), table_name='pooja_bookings')
    op.create_unique_constraint(None, 'pooja_bookings', ['booking_id'])
    op.drop_constraint(op.f('pooja_bookings_temple_id_fkey'), 'pooja_bookings', type_='foreignkey')
    op.drop_constraint(op.f('pooja_bookings_pooja_service_id_fkey'), 'pooja_bookings', type_='foreignkey')
    op.drop_constraint(op.f('pooja_bookings_booking_id_fkey'), 'pooja_bookings', type_='foreignkey')
    op.drop_constraint(op.f('pooja_bookings_slot_id_fkey'), 'pooja_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'pooja_bookings', 'pooja_services', ['pooja_service_id'], ['id'])
    op.create_foreign_key(None, 'pooja_bookings', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'pooja_bookings', 'pooja_slots', ['slot_id'], ['id'])
    op.create_foreign_key(None, 'pooja_bookings', 'temples', ['temple_id'], ['id'])
    op.alter_column('pooja_services', 'temple_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pooja_services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pooja_services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pooja_services', 'max_persons',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pooja_services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pooja_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pooja_services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_pooja_services_temple_id'), table_name='pooja_services')
    op.drop_constraint(op.f('pooja_services_temple_id_fkey'), 'pooja_services', type_='foreignkey')
    op.create_foreign_key(None, 'pooja_services', 'temples', ['temple_id'], ['id'])
    op.alter_column('pooja_slots', 'temple_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pooja_slots', 'pooja_service_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pooja_slots', 'slot_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('pooja_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('pooja_slots', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('pooja_slots', 'total_quota',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pooja_slots', 'booked_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pooja_slots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pooja_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pooja_slots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_pooja_slots_pooja_service_id'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_slots_slot_date'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_slots_temple_id'), table_name='pooja_slots')
    op.drop_constraint(op.f('pooja_slots_temple_id_fkey'), 'pooja_slots', type_='foreignkey')
    op.drop_constraint(op.f('pooja_slots_pooja_service_id_fkey'), 'pooja_slots', type_='foreignkey')
    op.create_foreign_key(None, 'pooja_slots', 'pooja_services', ['pooja_service_id'], ['id'])
    op.create_foreign_key(None, 'pooja_slots', 'temples', ['temple_id'], ['id'])
    op.alter_column('prasadam_items', 'temple_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prasadam_items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('prasadam_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prasadam_items', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('prasadam_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('prasadam_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_prasadam_items_temple_id'), table_name='prasadam_items')
    op.drop_constraint(op.f('prasadam_items_temple_id_fkey'), 'prasadam_items', type_='foreignkey')
    op.create_foreign_key(None, 'prasadam_items', 'temples', ['temple_id'], ['id'])
    op.alter_column('prasadam_order_items', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prasadam_order_items', 'item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prasadam_order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prasadam_order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prasadam_order_items', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prasadam_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_prasadam_order_items_order_id'), table_name='prasadam_order_items')
    op.drop_constraint(op.f('prasadam_order_items_item_id_fkey'), 'prasadam_order_items', type_='foreignkey')
    op.drop_constraint(op.f('prasadam_order_items_order_id_fkey'), 'prasadam_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'prasadam_order_items', 'prasadam_orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'prasadam_order_items', 'prasadam_items', ['item_id'], ['id'])
    op.add_column('prasadam_orders', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.alter_column('prasadam_orders', 'temple_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prasadam_orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prasadam_orders', 'order_reference',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('prasadam_orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prasadam_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('prasadam_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('prasadam_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_prasadam_orders_temple_id'), table_name='prasadam_orders')
    op.drop_index(op.f('ix_prasadam_orders_user_id'), table_name='prasadam_orders')
    op.drop_constraint(op.f('prasadam_orders_temple_id_fkey'), 'prasadam_orders', type_='foreignkey')
    op.create_foreign_key(None, 'prasadam_orders', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'prasadam_orders', 'temples', ['temple_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prasadam_orders', type_='foreignkey')
    op.drop_constraint(None, 'prasadam_orders', type_='foreignkey')
    op.create_foreign_key(op.f('prasadam_orders_temple_id_fkey'), 'prasadam_orders', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_prasadam_orders_user_id'), 'prasadam_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_prasadam_orders_temple_id'), 'prasadam_orders', ['temple_id'], unique=False)
    op.alter_column('prasadam_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('prasadam_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('prasadam_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('prasadam_orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prasadam_orders', 'order_reference',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('prasadam_orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('prasadam_orders', 'temple_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('prasadam_orders', 'booking_id')
    op.drop_constraint(None, 'prasadam_order_items', type_='foreignkey')
    op.drop_constraint(None, 'prasadam_order_items', type_='foreignkey')
    op.create_foreign_key(op.f('prasadam_order_items_order_id_fkey'), 'prasadam_order_items', 'prasadam_orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('prasadam_order_items_item_id_fkey'), 'prasadam_order_items', 'prasadam_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_prasadam_order_items_order_id'), 'prasadam_order_items', ['order_id'], unique=False)
    op.alter_column('prasadam_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('prasadam_order_items', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prasadam_order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prasadam_order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prasadam_order_items', 'item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('prasadam_order_items', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'prasadam_items', type_='foreignkey')
    op.create_foreign_key(op.f('prasadam_items_temple_id_fkey'), 'prasadam_items', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_prasadam_items_temple_id'), 'prasadam_items', ['temple_id'], unique=False)
    op.alter_column('prasadam_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('prasadam_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('prasadam_items', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('prasadam_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prasadam_items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('prasadam_items', 'temple_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'pooja_slots', type_='foreignkey')
    op.drop_constraint(None, 'pooja_slots', type_='foreignkey')
    op.create_foreign_key(op.f('pooja_slots_pooja_service_id_fkey'), 'pooja_slots', 'pooja_services', ['pooja_service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('pooja_slots_temple_id_fkey'), 'pooja_slots', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pooja_slots_temple_id'), 'pooja_slots', ['temple_id'], unique=False)
    op.create_index(op.f('ix_pooja_slots_slot_date'), 'pooja_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix_pooja_slots_pooja_service_id'), 'pooja_slots', ['pooja_service_id'], unique=False)
    op.alter_column('pooja_slots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pooja_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pooja_slots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pooja_slots', 'booked_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pooja_slots', 'total_quota',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pooja_slots', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('pooja_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('pooja_slots', 'slot_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('pooja_slots', 'pooja_service_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pooja_slots', 'temple_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'pooja_services', type_='foreignkey')
    op.create_foreign_key(op.f('pooja_services_temple_id_fkey'), 'pooja_services', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pooja_services_temple_id'), 'pooja_services', ['temple_id'], unique=False)
    op.alter_column('pooja_services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pooja_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pooja_services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pooja_services', 'max_persons',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pooja_services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pooja_services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('pooja_services', 'temple_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'pooja_bookings', type_='foreignkey')
    op.drop_constraint(None, 'pooja_bookings', type_='foreignkey')
    op.drop_constraint(None, 'pooja_bookings', type_='foreignkey')
    op.drop_constraint(None, 'pooja_bookings', type_='foreignkey')
    op.create_foreign_key(op.f('pooja_bookings_slot_id_fkey'), 'pooja_bookings', 'pooja_slots', ['slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('pooja_bookings_booking_id_fkey'), 'pooja_bookings', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('pooja_bookings_pooja_service_id_fkey'), 'pooja_bookings', 'pooja_services', ['pooja_service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('pooja_bookings_temple_id_fkey'), 'pooja_bookings', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pooja_bookings', type_='unique')
    op.create_index(op.f('ix_pooja_bookings_user_id'), 'pooja_bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_pooja_bookings_temple_id'), 'pooja_bookings', ['temple_id'], unique=False)
    op.create_index(op.f('ix_pooja_bookings_booking_id'), 'pooja_bookings', ['booking_id'], unique=True)
    op.alter_column('pooja_bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pooja_bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pooja_bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('pooja_bookings', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('pooja_bookings', 'num_persons',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pooja_bookings', 'booking_reference',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('pooja_bookings', 'pooja_service_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pooja_bookings', 'temple_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('darshan_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('darshan_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('darshan_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('darshan_types', 'max_persons_per_booking',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('darshan_types', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('darshan_types', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'darshan_slots', type_='foreignkey')
    op.drop_constraint(None, 'darshan_slots', type_='foreignkey')
    op.create_foreign_key(op.f('darshan_slots_darshan_type_id_fkey'), 'darshan_slots', 'darshan_types', ['darshan_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('darshan_slots_temple_id_fkey'), 'darshan_slots', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_darshan_slots_temple_id'), 'darshan_slots', ['temple_id'], unique=False)
    op.create_index(op.f('ix_darshan_slots_slot_date'), 'darshan_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix_darshan_slots_darshan_type_id'), 'darshan_slots', ['darshan_type_id'], unique=False)
    op.alter_column('darshan_slots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('darshan_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('darshan_slots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('darshan_slots', 'booked_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.create_foreign_key(op.f('darshan_bookings_darshan_type_id_fkey'), 'darshan_bookings', 'darshan_types', ['darshan_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('darshan_bookings_darshan_slot_id_fkey'), 'darshan_bookings', 'darshan_slots', ['darshan_slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('darshan_bookings_temple_id_fkey'), 'darshan_bookings', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'darshan_bookings', type_='unique')
    op.create_index(op.f('ix_darshan_bookings_temple_id'), 'darshan_bookings', ['temple_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_booking_id'), 'darshan_bookings', ['booking_id'], unique=True)
    op.alter_column('darshan_bookings', 'devotee_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('darshan_bookings', 'darshan_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('darshan_bookings', 'darshan_slot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('bookings', sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('paid_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('booking_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('cancellation_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('custom_trip_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('booking_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('special_requests', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('coupon_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('convenience_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('contact_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.create_unique_constraint(op.f('bookings_booking_number_key'), 'bookings', ['booking_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               nullable=False)
    # ### end Alembic commands ###
