"""add audit_logs table

Revision ID: 19a830da9ae7
Revises: 365dbb468805
Create Date: 2026-04-17 14:47:58.459724

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '19a830da9ae7'
down_revision: Union[str, None] = '365dbb468805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
