"""add coupon tables

Revision ID: 2ab3eefe8be4
Revises: f2a20371655a
Create Date: 2026-03-23 20:30:07.653366

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2ab3eefe8be4'
down_revision: Union[str, None] = 'f2a20371655a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(), nullable=False),
    sa.Column('min_order_value', sa.Numeric(), nullable=True),
    sa.Column('max_discount', sa.Numeric(), nullable=True),
    sa.Column('applicable_to', sa.String(), nullable=True),
    sa.Column('applicable_on', sa.String(length=20), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_per_user', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_referral', sa.Boolean(), nullable=True),
    sa.Column('coupon_type', sa.String(length=20), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('applicable_user_ids', sa.JSON(), nullable=True),
    sa.Column('referral_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('coupon_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('order_value', sa.Float(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_usages_coupon_id'), 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_user_id'), 'coupon_usages', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_user_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=True),
    sa.Column('coupon_id', sa.UUID(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('referrer_reward', sa.Float(), nullable=True),
    sa.Column('referred_reward', sa.Float(), nullable=True),
    sa.Column('is_redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.drop_constraint(op.f('bookings_booking_id_key'), 'bookings', type_='unique')
    op.drop_index(op.f('ix_bookings_payment_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_dates'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_type'), table_name='bookings')
    op.drop_constraint(op.f('bookings_booking_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'booking_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('bookings_booking_id_fkey'), 'bookings', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_bookings_user_type'), 'bookings', ['user_id', 'booking_type'], unique=False)
    op.create_index(op.f('ix_bookings_user_status'), 'bookings', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_user_dates'), 'bookings', ['user_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_bookings_payment_status'), 'bookings', ['payment_status'], unique=False)
    op.create_unique_constraint(op.f('bookings_booking_id_key'), 'bookings', ['booking_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_coupon_usages_user_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_coupon_id'), table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
