"""add destination_id to hotels

Revision ID: 35fa012b4b53
Revises: a3f1c9e2b841
Create Date: 2026-04-13 08:53:36.224126

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '35fa012b4b53'
down_revision: Union[str, None] = 'a3f1c9e2b841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklisted_tokens_jti'), 'blacklisted_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_blacklisted_tokens_user_id'), 'blacklisted_tokens', ['user_id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.String(length=5), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_id'), 'tracking_events', ['id'], unique=False)
    op.create_table('temple_pooja_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'),
               nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bookings', 'booking_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('bookings', 'special_requests',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('bookings', 'contact_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('bookings', 'custom_trip_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.create_index('ix_bookings_booking_number', 'bookings', ['booking_number'], unique=False)
    op.create_unique_constraint(None, 'bookings', ['booking_number'])
    op.drop_column('coupons', 'max_uses_per_user')
    op.add_column('darshan_bookings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('darshan_bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('darshan_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('darshan_bookings_booking_id_key'), 'darshan_bookings', type_='unique')
    op.create_index(op.f('ix_darshan_bookings_booking_id'), 'darshan_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_darshan_bookings_darshan_slot_id'), 'darshan_bookings', ['darshan_slot_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_darshan_type_id'), 'darshan_bookings', ['darshan_type_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_temple_id'), 'darshan_bookings', ['temple_id'], unique=False)
    op.create_index(op.f('ix_darshan_slots_darshan_type_id'), 'darshan_slots', ['darshan_type_id'], unique=False)
    op.create_index('ix_darshan_slots_temple_date', 'darshan_slots', ['temple_id', 'slot_date'], unique=False)
    op.create_index(op.f('ix_darshan_slots_temple_id'), 'darshan_slots', ['temple_id'], unique=False)
    op.drop_constraint(op.f('hotel_bookings_booking_number_key'), 'hotel_bookings', type_='unique')
    op.drop_column('hotel_bookings', 'booking_number')
    op.add_column('hotels', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.alter_column('hotels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_hotels_destination_id'), 'hotels', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'hotels', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.alter_column('partners', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pooja_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('pooja_bookings_booking_id_key'), 'pooja_bookings', type_='unique')
    op.create_index(op.f('ix_pooja_bookings_booking_id'), 'pooja_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_pooja_bookings_pooja_service_id'), 'pooja_bookings', ['pooja_service_id'], unique=False)
    op.create_index(op.f('ix_pooja_bookings_temple_id'), 'pooja_bookings', ['temple_id'], unique=False)
    op.drop_column('pooja_bookings', 'status')
    op.drop_column('pooja_bookings', 'user_id')
    op.drop_column('pooja_bookings', 'total_amount')
    op.drop_column('pooja_bookings', 'devotee_name')
    op.drop_column('pooja_bookings', 'payment_id')
    op.create_index(op.f('ix_pooja_services_temple_id'), 'pooja_services', ['temple_id'], unique=False)
    op.create_index(op.f('ix_pooja_slots_pooja_service_id'), 'pooja_slots', ['pooja_service_id'], unique=False)
    op.create_index(op.f('ix_pooja_slots_temple_id'), 'pooja_slots', ['temple_id'], unique=False)
    op.create_index(op.f('ix_prasadam_items_temple_id'), 'prasadam_items', ['temple_id'], unique=False)
    op.create_index(op.f('ix_prasadam_order_items_item_id'), 'prasadam_order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_prasadam_order_items_order_id'), 'prasadam_order_items', ['order_id'], unique=False)
    op.alter_column('prasadam_orders', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prasadam_orders', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('prasadam_orders', 'delivery_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_prasadam_orders_booking_id'), 'prasadam_orders', ['booking_id'], unique=False)
    op.create_index(op.f('ix_prasadam_orders_temple_id'), 'prasadam_orders', ['temple_id'], unique=False)
    op.create_index('ix_prasadam_orders_temple_user', 'prasadam_orders', ['temple_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_prasadam_orders_user_id'), 'prasadam_orders', ['user_id'], unique=False)
    op.drop_column('prasadam_orders', 'payment_id')
    op.execute("CREATE TYPE trackerrole AS ENUM ('DRIVER', 'GUIDE')")
    op.execute("ALTER TABLE tracking_sessions ALTER COLUMN tracker_role TYPE trackerrole USING tracker_role::trackerrole")
    op.alter_column('tracking_sessions', 'tracker_role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRIVER', 'GUIDE', name='trackerrole'),
               existing_nullable=False)
    op.alter_column('vehicle_bookings', 'pickup_lat',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'pickup_lng',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'driver_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'toll_charges',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.drop_column('vehicle_bookings', 'dropoff_lat')
    op.drop_column('vehicle_bookings', 'dropoff_lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_bookings', sa.Column('dropoff_lng', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True))
    op.add_column('vehicle_bookings', sa.Column('dropoff_lat', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True))
    op.alter_column('vehicle_bookings', 'toll_charges',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'driver_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'pickup_lng',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'pickup_lat',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.execute("ALTER TABLE tracking_sessions ALTER COLUMN tracker_role TYPE VARCHAR(20) USING tracker_role::text")
    op.execute("DROP TYPE IF EXISTS trackerrole")
    op.alter_column('tracking_sessions', 'tracker_role',
               existing_type=sa.Enum('DRIVER', 'GUIDE', name='trackerrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('prasadam_orders', sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_prasadam_orders_user_id'), table_name='prasadam_orders')
    op.drop_index('ix_prasadam_orders_temple_user', table_name='prasadam_orders')
    op.drop_index(op.f('ix_prasadam_orders_temple_id'), table_name='prasadam_orders')
    op.drop_index(op.f('ix_prasadam_orders_booking_id'), table_name='prasadam_orders')
    op.alter_column('prasadam_orders', 'delivery_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('prasadam_orders', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('prasadam_orders', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_prasadam_order_items_order_id'), table_name='prasadam_order_items')
    op.drop_index(op.f('ix_prasadam_order_items_item_id'), table_name='prasadam_order_items')
    op.drop_index(op.f('ix_prasadam_items_temple_id'), table_name='prasadam_items')
    op.drop_index(op.f('ix_pooja_slots_temple_id'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_slots_pooja_service_id'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_services_temple_id'), table_name='pooja_services')
    op.add_column('pooja_bookings', sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pooja_bookings', sa.Column('devotee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pooja_bookings', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pooja_bookings', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('pooja_bookings', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pooja_bookings_temple_id'), table_name='pooja_bookings')
    op.drop_index(op.f('ix_pooja_bookings_pooja_service_id'), table_name='pooja_bookings')
    op.drop_index(op.f('ix_pooja_bookings_booking_id'), table_name='pooja_bookings')
    op.create_unique_constraint(op.f('pooja_bookings_booking_id_key'), 'pooja_bookings', ['booking_id'])
    op.alter_column('pooja_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('partners', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_index(op.f('ix_hotels_destination_id'), table_name='hotels')
    op.alter_column('hotels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('hotels', 'destination_id')
    op.add_column('hotel_bookings', sa.Column('booking_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('hotel_bookings_booking_number_key'), 'hotel_bookings', ['booking_number'])
    op.drop_index(op.f('ix_darshan_slots_temple_id'), table_name='darshan_slots')
    op.drop_index('ix_darshan_slots_temple_date', table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_slots_darshan_type_id'), table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_bookings_temple_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_darshan_type_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_darshan_slot_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_booking_id'), table_name='darshan_bookings')
    op.create_unique_constraint(op.f('darshan_bookings_booking_id_key'), 'darshan_bookings', ['booking_id'])
    op.alter_column('darshan_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('darshan_bookings', 'updated_at')
    op.drop_column('darshan_bookings', 'created_at')
    op.add_column('coupons', sa.Column('max_uses_per_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_index('ix_bookings_booking_number', table_name='bookings')
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.alter_column('bookings', 'custom_trip_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('bookings', 'contact_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('bookings', 'special_requests',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('bookings', 'booking_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'),
               nullable=True)
    op.drop_table('temple_pooja_services')
    op.drop_index(op.f('ix_tracking_events_id'), table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_blacklisted_tokens_user_id'), table_name='blacklisted_tokens')
    op.drop_index(op.f('ix_blacklisted_tokens_jti'), table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
