"""add destination tables

Revision ID: 5635d7d13469
Revises: 73f487b90c5b
Create Date: 2026-03-23 09:54:08.315106

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5635d7d13469'
down_revision: Union[str, None] = '73f487b90c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('NATURE', 'HERITAGE', 'ADVENTURE', 'COASTAL', 'RELIGIOUS', name='destinationtype'), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('best_season', sa.String(length=100), nullable=True),
    sa.Column('temperature_range', sa.String(length=50), nullable=True),
    sa.Column('how_to_reach', sa.JSON(), nullable=True),
    sa.Column('attractions', sa.JSON(), nullable=False),
    sa.Column('nearby_temples', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_destinations_district'), 'destinations', ['district'], unique=False)
    op.create_index(op.f('ix_destinations_is_active'), 'destinations', ['is_active'], unique=False)
    op.create_index(op.f('ix_destinations_is_featured'), 'destinations', ['is_featured'], unique=False)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_index(op.f('ix_destinations_type'), 'destinations', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinations_type'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_is_featured'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_is_active'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_district'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
