"""fix darshan foreign key

Revision ID: 56f9f1c23db1
Revises: 83449e203f73
Create Date: 2026-03-23 18:14:37.360658

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '56f9f1c23db1'
down_revision: Union[str, None] = '83449e203f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               server_default=None,
               existing_nullable=False)
    op.create_index('ix_bookings_payment_status', 'bookings', ['payment_status'], unique=False)
    op.drop_index(op.f('ix_darshan_bookings_darshan_slot_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_darshan_type_id'), table_name='darshan_bookings')
    op.drop_constraint(op.f('darshan_bookings_booking_id_fkey'), 'darshan_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'darshan_bookings', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'darshan_bookings', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'darshan_bookings', 'darshan_slots', ['darshan_slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'darshan_bookings', 'darshan_types', ['darshan_type_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refunds', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('refunds', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('refunds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('saved_cards', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('saved_cards', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('saved_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('saved_cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('transactions', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               server_default=sa.text("'INITIATED'::paymentstatus"),
               existing_nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('saved_cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('saved_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('saved_cards', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('saved_cards', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('refunds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('refunds', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('refunds', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.drop_constraint(None, 'darshan_bookings', type_='foreignkey')
    op.create_foreign_key(op.f('darshan_bookings_booking_id_fkey'), 'darshan_bookings', 'bookings', ['booking_id'], ['id'])
    op.create_index(op.f('ix_darshan_bookings_darshan_type_id'), 'darshan_bookings', ['darshan_type_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_darshan_slot_id'), 'darshan_bookings', ['darshan_slot_id'], unique=False)
    op.drop_index('ix_bookings_payment_status', table_name='bookings')
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               server_default=sa.text("'INITIATED'::paymentstatus"),
               existing_nullable=False)
    # ### end Alembic commands ###
