"""add admin  tables

Revision ID: 8281310bd86a
Revises: 228cfee71d69
Create Date: 2026-03-24 16:02:12.182200

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '8281310bd86a'
down_revision: Union[str, None] = '228cfee71d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.Enum('HOTEL', 'TEMPLE', 'GUIDE', 'PACKAGE', 'VEHICLE', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FLAGGED', 'REMOVED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'booking_id', 'entity_type', 'entity_id', name='uq_review_user_booking_entity')
    )
    op.create_index('ix_reviews_entity', 'reviews', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('review_helpfuls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_review_helpful_user')
    )
    op.create_table('review_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'OFFENSIVE', 'FAKE', 'IRRELEVANT', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'reported_by', name='uq_report_user_review')
    )
    op.create_index(op.f('ix_location_history_session_id'), 'location_history', ['session_id'], unique=False)
    op.alter_column('notification_preferences', 'push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'sms_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'type_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('notification_preferences_user_id_key'), 'notification_preferences', type_='unique')
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_support_tickets_ticket_number'), 'support_tickets', type_='unique')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.alter_column('ticket_messages', 'sender_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ticket_messages', 'is_internal',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_ticket_messages_created_at'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_sender_id'), table_name='ticket_messages')

    trackingsessionstatus = sa.Enum(
    'ACTIVE',
    'PAUSED',
    'COMPLETED',
    'CANCELLED',
    name='trackingsessionstatus'
)

    trackingsessionstatus.create(op.get_bind(), checkfirst=True)

    # remove default first
    op.execute(
    "ALTER TABLE tracking_sessions ALTER COLUMN status DROP DEFAULT"
)

# convert column type
    op.execute(
    "ALTER TABLE tracking_sessions "
    "ALTER COLUMN status TYPE trackingsessionstatus "
    "USING status::trackingsessionstatus"
)

# add default again
    op.execute(
    "ALTER TABLE tracking_sessions "
    "ALTER COLUMN status SET DEFAULT 'ACTIVE'"
)
    op.alter_column('tracking_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='trackingsessionstatus'),
               existing_nullable=False)
    op.alter_column('tracking_sessions', 'share_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('tracking_sessions_booking_id_key'), 'tracking_sessions', type_='unique')
    op.drop_constraint(op.f('tracking_sessions_share_token_key'), 'tracking_sessions', type_='unique')
    op.drop_index(op.f('ix_tracking_sessions_booking_id'), table_name='tracking_sessions')
    op.create_index(op.f('ix_tracking_sessions_booking_id'), 'tracking_sessions', ['booking_id'], unique=True)
    op.drop_index(op.f('ix_tracking_sessions_share_token'), table_name='tracking_sessions')
    op.create_index(op.f('ix_tracking_sessions_share_token'), 'tracking_sessions', ['share_token'], unique=True)
    op.drop_constraint(op.f('trip_locations_session_id_key'), 'trip_locations', type_='unique')
    op.drop_index(op.f('ix_trip_locations_session_id'), table_name='trip_locations')
    op.create_index(op.f('ix_trip_locations_session_id'), 'trip_locations', ['session_id'], unique=True)
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trip_locations_session_id'), table_name='trip_locations')
    op.create_index(op.f('ix_trip_locations_session_id'), 'trip_locations', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('trip_locations_session_id_key'), 'trip_locations', ['session_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tracking_sessions_share_token'), table_name='tracking_sessions')
    op.create_index(op.f('ix_tracking_sessions_share_token'), 'tracking_sessions', ['share_token'], unique=False)
    op.drop_index(op.f('ix_tracking_sessions_booking_id'), table_name='tracking_sessions')
    op.create_index(op.f('ix_tracking_sessions_booking_id'), 'tracking_sessions', ['booking_id'], unique=False)
    op.create_unique_constraint(op.f('tracking_sessions_share_token_key'), 'tracking_sessions', ['share_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tracking_sessions_booking_id_key'), 'tracking_sessions', ['booking_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tracking_sessions', 'share_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('tracking_sessions', 'status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='trackingsessionstatus'),
               server_default=sa.text("'ACTIVE'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('tracking_sessions', 'tracker_role',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='trackingsessionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_ticket_messages_sender_id'), 'ticket_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_created_at'), 'ticket_messages', ['created_at'], unique=False)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('ticket_messages', 'is_internal',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ticket_messages', 'sender_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=False)
    op.create_unique_constraint(op.f('uq_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'in_app'::character varying"),
               existing_nullable=False)
    op.create_unique_constraint(op.f('notification_preferences_user_id_key'), 'notification_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('notification_preferences', 'type_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'sms_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_location_history_session_id'), table_name='location_history')
    op.drop_table('review_reports')
    op.drop_table('review_helpfuls')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_entity', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
