"""add search tables

Revision ID: 879b92c14c55
Revises: f34d11135618
Create Date: 2026-03-24 13:01:17.946384

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '879b92c14c55'
down_revision: Union[str, None] = 'f34d11135618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
