"""hotel_guide_temple

Revision ID: 93402bd1e2c5
Revises: fc2c00c13f3c
Create Date: 2026-04-14 16:06:18.258638

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '93402bd1e2c5'
down_revision: Union[str, None] = 'fc2c00c13f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_destinations_fts', table_name='destinations', postgresql_using='gin')
    op.drop_index('idx_destinations_name_trgm', table_name='destinations', postgresql_using='gin')
    op.add_column('guides', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_guides_destination_id'), 'guides', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'guides', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.add_column('hotels', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.drop_index('idx_hotels_fts', table_name='hotels', postgresql_using='gin')
    op.drop_index('idx_hotels_name_trgm', table_name='hotels', postgresql_using='gin')
    op.create_index(op.f('ix_hotels_destination_id'), 'hotels', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'hotels', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_packages_fts', table_name='packages', postgresql_using='gin')
    op.drop_index('idx_packages_name_trgm', table_name='packages', postgresql_using='gin')
    op.add_column('temples', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.drop_index('idx_temples_fts', table_name='temples', postgresql_using='gin')
    op.drop_index('idx_temples_name_trgm', table_name='temples', postgresql_using='gin')
    op.create_index(op.f('ix_temples_destination_id'), 'temples', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'temples', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temples', type_='foreignkey')
    op.drop_index(op.f('ix_temples_destination_id'), table_name='temples')
    op.create_index('idx_temples_name_trgm', 'temples', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_temples_fts', 'temples', [sa.text("to_tsvector('english'::regconfig, (((((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(deity, ''::character varying)::text) || ' '::text) || COALESCE(district, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('temples', 'destination_id')
    op.create_index('idx_packages_name_trgm', 'packages', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_packages_fts', 'packages', [sa.text("to_tsvector('english'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(slug, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_index(op.f('ix_hotels_destination_id'), table_name='hotels')
    op.create_index('idx_hotels_name_trgm', 'hotels', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_hotels_fts', 'hotels', [sa.text("to_tsvector('english'::regconfig, (((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(city, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('hotels', 'destination_id')
    op.drop_constraint(None, 'guides', type_='foreignkey')
    op.drop_index(op.f('ix_guides_destination_id'), table_name='guides')
    op.drop_column('guides', 'destination_id')
    op.create_index('idx_destinations_name_trgm', 'destinations', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_destinations_fts', 'destinations', [sa.text("to_tsvector('english'::regconfig, (((((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(tagline, ''::character varying)::text) || ' '::text) || COALESCE(district, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
