"""add booking tables

Revision ID: 9742f2ae52f7
Revises: 0452a0f92a7e
Create Date: 2026-03-23 14:45:06.121632

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9742f2ae52f7'
down_revision: Union[str, None] = '0452a0f92a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
