"""add destination_id to guides

Revision ID: 976c49be93fd
Revises: 35fa012b4b53
Create Date: 2026-04-13 09:09:54.414416

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '976c49be93fd'
down_revision: Union[str, None] = '35fa012b4b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_guides_destination_id'), 'guides', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'guides', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guides', type_='foreignkey')
    op.drop_index(op.f('ix_guides_destination_id'), table_name='guides')
    op.drop_column('guides', 'destination_id')
    # ### end Alembic commands ###
