"""add destination_id to temples

Revision ID: 97fa3ee5e04e
Revises: 976c49be93fd
Create Date: 2026-04-13 09:17:35.998747

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '97fa3ee5e04e'
down_revision: Union[str, None] = '976c49be93fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temples', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_temples_destination_id'), 'temples', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'temples', 'destinations', ['destination_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temples', type_='foreignkey')
    op.drop_index(op.f('ix_temples_destination_id'), table_name='temples')
    op.drop_column('temples', 'destination_id')
    # ### end Alembic commands ###
