"""add_fcm_token_to_user_profiles

Revision ID: a43f96437ca0
Revises: 3f036d4ec9ba
Create Date: 2026-04-21 10:31:59.588510

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a43f96437ca0'
down_revision: Union[str, None] = '3f036d4ec9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('fcm_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'fcm_token')
    # ### end Alembic commands ###
