"""schema_sync_tracking_darshan_pooja

Revision ID: c7da0f4c4805
Revises: a3f1c9e2b841
Create Date: 2026-04-10 08:49:15.522913

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c7da0f4c4805'
down_revision: Union[str, None] = 'a3f1c9e2b841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temple_pooja_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bookings', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bookings', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bookings', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bookings', 'convenience_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bookings', 'paid_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_bookings_booking_number', table_name='bookings')
    op.create_index('ix_bookings_booking_number', 'bookings', ['booking_number'], unique=False)
    op.add_column('coupons', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.add_column('darshan_bookings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('darshan_bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('darshan_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('darshan_bookings_booking_id_key', 'darshan_bookings', type_='unique')
    op.create_index(op.f('ix_darshan_bookings_booking_id'), 'darshan_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_darshan_bookings_darshan_slot_id'), 'darshan_bookings', ['darshan_slot_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_darshan_type_id'), 'darshan_bookings', ['darshan_type_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_temple_id'), 'darshan_bookings', ['temple_id'], unique=False)
    op.create_index(op.f('ix_darshan_slots_darshan_type_id'), 'darshan_slots', ['darshan_type_id'], unique=False)
    op.create_index('ix_darshan_slots_temple_date', 'darshan_slots', ['temple_id', 'slot_date'], unique=False)
    op.create_index(op.f('ix_darshan_slots_temple_id'), 'darshan_slots', ['temple_id'], unique=False)
    op.alter_column('hotels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('partners', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pooja_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('pooja_bookings_booking_id_key', 'pooja_bookings', type_='unique')
    op.create_index(op.f('ix_pooja_bookings_booking_id'), 'pooja_bookings', ['booking_id'], unique=True)
    op.create_index(op.f('ix_pooja_bookings_pooja_service_id'), 'pooja_bookings', ['pooja_service_id'], unique=False)
    op.create_index(op.f('ix_pooja_bookings_temple_id'), 'pooja_bookings', ['temple_id'], unique=False)
    op.drop_column('pooja_bookings', 'status')
    op.drop_column('pooja_bookings', 'user_id')
    op.drop_column('pooja_bookings', 'total_amount')
    op.drop_column('pooja_bookings', 'payment_id')
    op.drop_column('pooja_bookings', 'devotee_name')
    op.create_index(op.f('ix_pooja_services_temple_id'), 'pooja_services', ['temple_id'], unique=False)
    op.create_index(op.f('ix_pooja_slots_pooja_service_id'), 'pooja_slots', ['pooja_service_id'], unique=False)
    op.create_index(op.f('ix_pooja_slots_temple_id'), 'pooja_slots', ['temple_id'], unique=False)
    op.create_index(op.f('ix_prasadam_items_temple_id'), 'prasadam_items', ['temple_id'], unique=False)
    op.create_index(op.f('ix_prasadam_order_items_item_id'), 'prasadam_order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_prasadam_order_items_order_id'), 'prasadam_order_items', ['order_id'], unique=False)
    op.alter_column('prasadam_orders', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prasadam_orders', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('prasadam_orders', 'delivery_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_prasadam_orders_booking_id'), 'prasadam_orders', ['booking_id'], unique=False)
    op.create_index(op.f('ix_prasadam_orders_temple_id'), 'prasadam_orders', ['temple_id'], unique=False)
    op.create_index('ix_prasadam_orders_temple_user', 'prasadam_orders', ['temple_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_prasadam_orders_user_id'), 'prasadam_orders', ['user_id'], unique=False)
    op.drop_column('prasadam_orders', 'payment_id')
    trackerrole_enum = sa.Enum('DRIVER', 'GUIDE', name='trackerrole')
    trackerrole_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('tracking_sessions', 'tracker_role',
           existing_type=sa.VARCHAR(length=20),
           type_=sa.Enum('DRIVER', 'GUIDE', name='trackerrole'),
           existing_nullable=False,
           postgresql_using="tracker_role::trackerrole")
    op.alter_column('vehicle_bookings', 'driver_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'toll_charges',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_bookings', 'toll_charges',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'driver_allowance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('tracking_sessions', 'tracker_role',
           existing_type=sa.Enum('DRIVER', 'GUIDE', name='trackerrole'),
           type_=sa.VARCHAR(length=20),
           existing_nullable=False,
           postgresql_using="tracker_role::varchar")

    sa.Enum(name='trackerrole').drop(op.get_bind(), checkfirst=True)
    op.add_column('prasadam_orders', sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_prasadam_orders_user_id'), table_name='prasadam_orders')
    op.drop_index('ix_prasadam_orders_temple_user', table_name='prasadam_orders')
    op.drop_index(op.f('ix_prasadam_orders_temple_id'), table_name='prasadam_orders')
    op.drop_index(op.f('ix_prasadam_orders_booking_id'), table_name='prasadam_orders')
    op.alter_column('prasadam_orders', 'delivery_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('prasadam_orders', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('prasadam_orders', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_prasadam_order_items_order_id'), table_name='prasadam_order_items')
    op.drop_index(op.f('ix_prasadam_order_items_item_id'), table_name='prasadam_order_items')
    op.drop_index(op.f('ix_prasadam_items_temple_id'), table_name='prasadam_items')
    op.drop_index(op.f('ix_pooja_slots_temple_id'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_slots_pooja_service_id'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_services_temple_id'), table_name='pooja_services')
    op.add_column('pooja_bookings', sa.Column('devotee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pooja_bookings', sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pooja_bookings', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pooja_bookings', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('pooja_bookings', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pooja_bookings_temple_id'), table_name='pooja_bookings')
    op.drop_index(op.f('ix_pooja_bookings_pooja_service_id'), table_name='pooja_bookings')
    op.drop_index(op.f('ix_pooja_bookings_booking_id'), table_name='pooja_bookings')
    op.create_unique_constraint('pooja_bookings_booking_id_key', 'pooja_bookings', ['booking_id'])
    op.alter_column('pooja_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('partners', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('hotels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_darshan_slots_temple_id'), table_name='darshan_slots')
    op.drop_index('ix_darshan_slots_temple_date', table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_slots_darshan_type_id'), table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_bookings_temple_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_darshan_type_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_darshan_slot_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_booking_id'), table_name='darshan_bookings')
    op.create_unique_constraint('darshan_bookings_booking_id_key', 'darshan_bookings', ['booking_id'])
    op.alter_column('darshan_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('darshan_bookings', 'updated_at')
    op.drop_column('darshan_bookings', 'created_at')
    op.drop_column('coupons', 'max_uses')
    op.drop_index('ix_bookings_booking_number', table_name='bookings')
    op.create_index('ix_bookings_booking_number', 'bookings', ['booking_number'], unique=True)
    op.alter_column('bookings', 'paid_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('bookings', 'convenience_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('bookings', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('bookings', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('bookings', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'),
               nullable=True)
    op.drop_table('temple_pooja_services')
    # ### end Alembic commands ###
