"""add packages

Revision ID: de7b01f846d0
Revises: 5635d7d13469
Create Date: 2026-03-23 11:02:21.896160

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'de7b01f846d0'
down_revision: Union[str, None] = '5635d7d13469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PILGRIMAGE', 'LEISURE', 'ADVENTURE', name='packagetype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('itinerary', sa.JSON(), nullable=False),
    sa.Column('inclusions', sa.JSON(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('pricing_rules', sa.JSON(), nullable=True),
    sa.Column('departure_dates', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_is_active'), 'packages', ['is_active'], unique=False)
    op.create_index(op.f('ix_packages_is_featured'), 'packages', ['is_featured'], unique=False)
    op.create_index(op.f('ix_packages_slug'), 'packages', ['slug'], unique=True)
    op.create_index(op.f('ix_packages_type'), 'packages', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_type'), table_name='packages')
    op.drop_index(op.f('ix_packages_slug'), table_name='packages')
    op.drop_index(op.f('ix_packages_is_featured'), table_name='packages')
    op.drop_index(op.f('ix_packages_is_active'), table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
