"""add partners tables

Revision ID: e87378aee423
Revises: f7e9ab2f9469
Create Date: 2026-03-17 14:11:08.021006

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e87378aee423'
down_revision: Union[str, None] = 'f7e9ab2f9469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
