"""create tables

Revision ID: ed5968b8047b
Revises: 
Create Date: 2026-03-18 15:46:27.027580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5968b8047b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deity', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('dress_code', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('booking_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temples_deity'), 'temples', ['deity'], unique=False)
    op.create_index(op.f('ix_temples_district'), 'temples', ['district'], unique=False)
    op.create_index(op.f('ix_temples_name'), 'temples', ['name'], unique=False)
    op.create_table('darshan_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('darshan_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('what_is_included', sa.Text(), nullable=True),
    sa.Column('max_persons_per_booking', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_darshan_types_darshan_type'), 'darshan_types', ['darshan_type'], unique=False)
    op.create_index(op.f('ix_darshan_types_temple_id'), 'darshan_types', ['temple_id'], unique=False)
    op.create_table('pooja_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('items_included', sa.Text(), nullable=True),
    sa.Column('priest_requirements', sa.Text(), nullable=True),
    sa.Column('max_persons', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pooja_services_temple_id'), 'pooja_services', ['temple_id'], unique=False)
    op.create_table('prasadam_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prasadam_items_temple_id'), 'prasadam_items', ['temple_id'], unique=False)
    op.create_table('prasadam_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_reference', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_reference')
    )
    op.create_index(op.f('ix_prasadam_orders_temple_id'), 'prasadam_orders', ['temple_id'], unique=False)
    op.create_index(op.f('ix_prasadam_orders_user_id'), 'prasadam_orders', ['user_id'], unique=False)
    op.create_table('temple_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_events_temple_id'), 'temple_events', ['temple_id'], unique=False)
    op.create_table('temple_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_reviews_temple_id'), 'temple_reviews', ['temple_id'], unique=False)
    op.create_index(op.f('ix_temple_reviews_user_id'), 'temple_reviews', ['user_id'], unique=False)
    op.create_table('darshan_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('darshan_type_id', sa.UUID(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_quota', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['darshan_type_id'], ['darshan_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_darshan_slots_darshan_type_id'), 'darshan_slots', ['darshan_type_id'], unique=False)
    op.create_index(op.f('ix_darshan_slots_slot_date'), 'darshan_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix_darshan_slots_temple_id'), 'darshan_slots', ['temple_id'], unique=False)
    op.create_table('pooja_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('pooja_service_id', sa.UUID(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_quota', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pooja_service_id'], ['pooja_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pooja_slots_pooja_service_id'), 'pooja_slots', ['pooja_service_id'], unique=False)
    op.create_index(op.f('ix_pooja_slots_slot_date'), 'pooja_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix_pooja_slots_temple_id'), 'pooja_slots', ['temple_id'], unique=False)
    op.create_table('prasadam_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['prasadam_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['prasadam_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prasadam_order_items_order_id'), 'prasadam_order_items', ['order_id'], unique=False)
    op.create_table('darshan_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('num_persons', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('pilgrim_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['darshan_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_darshan_bookings_booking_reference'), 'darshan_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_darshan_bookings_slot_id'), 'darshan_bookings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_temple_id'), 'darshan_bookings', ['temple_id'], unique=False)
    op.create_index(op.f('ix_darshan_bookings_user_id'), 'darshan_bookings', ['user_id'], unique=False)
    op.create_table('pooja_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('pooja_service_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('num_persons', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('devotee_name', sa.String(length=255), nullable=True),
    sa.Column('gotram', sa.String(length=100), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pooja_service_id'], ['pooja_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['pooja_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index(op.f('ix_pooja_bookings_temple_id'), 'pooja_bookings', ['temple_id'], unique=False)
    op.create_index(op.f('ix_pooja_bookings_user_id'), 'pooja_bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pooja_bookings_user_id'), table_name='pooja_bookings')
    op.drop_index(op.f('ix_pooja_bookings_temple_id'), table_name='pooja_bookings')
    op.drop_table('pooja_bookings')
    op.drop_index(op.f('ix_darshan_bookings_user_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_temple_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_slot_id'), table_name='darshan_bookings')
    op.drop_index(op.f('ix_darshan_bookings_booking_reference'), table_name='darshan_bookings')
    op.drop_table('darshan_bookings')
    op.drop_index(op.f('ix_prasadam_order_items_order_id'), table_name='prasadam_order_items')
    op.drop_table('prasadam_order_items')
    op.drop_index(op.f('ix_pooja_slots_temple_id'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_slots_slot_date'), table_name='pooja_slots')
    op.drop_index(op.f('ix_pooja_slots_pooja_service_id'), table_name='pooja_slots')
    op.drop_table('pooja_slots')
    op.drop_index(op.f('ix_darshan_slots_temple_id'), table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_slots_slot_date'), table_name='darshan_slots')
    op.drop_index(op.f('ix_darshan_slots_darshan_type_id'), table_name='darshan_slots')
    op.drop_table('darshan_slots')
    op.drop_index(op.f('ix_temple_reviews_user_id'), table_name='temple_reviews')
    op.drop_index(op.f('ix_temple_reviews_temple_id'), table_name='temple_reviews')
    op.drop_table('temple_reviews')
    op.drop_index(op.f('ix_temple_events_temple_id'), table_name='temple_events')
    op.drop_table('temple_events')
    op.drop_index(op.f('ix_prasadam_orders_user_id'), table_name='prasadam_orders')
    op.drop_index(op.f('ix_prasadam_orders_temple_id'), table_name='prasadam_orders')
    op.drop_table('prasadam_orders')
    op.drop_index(op.f('ix_prasadam_items_temple_id'), table_name='prasadam_items')
    op.drop_table('prasadam_items')
    op.drop_index(op.f('ix_pooja_services_temple_id'), table_name='pooja_services')
    op.drop_table('pooja_services')
    op.drop_index(op.f('ix_darshan_types_temple_id'), table_name='darshan_types')
    op.drop_index(op.f('ix_darshan_types_darshan_type'), table_name='darshan_types')
    op.drop_table('darshan_types')
    op.drop_index(op.f('ix_temples_name'), table_name='temples')
    op.drop_index(op.f('ix_temples_district'), table_name='temples')
    op.drop_index(op.f('ix_temples_deity'), table_name='temples')
    op.drop_table('temples')
    # ### end Alembic commands ###
