"""fix pooja booking relation

Revision ID: f2a20371655a
Revises: 56f9f1c23db1
Create Date: 2026-03-23 18:25:41.748688

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f2a20371655a'
down_revision: Union[str, None] = '56f9f1c23db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'bookings', ['booking_id'])
    op.create_foreign_key(None, 'bookings', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.add_column('pooja_bookings', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_pooja_bookings_booking_id'), 'pooja_bookings', ['booking_id'], unique=True)
    op.create_foreign_key(None, 'pooja_bookings', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pooja_bookings', type_='foreignkey')
    op.drop_index(op.f('ix_pooja_bookings_booking_id'), table_name='pooja_bookings')
    op.drop_column('pooja_bookings', 'booking_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_column('bookings', 'booking_id')
    # ### end Alembic commands ###
