"""add reviews tables

Revision ID: f34d11135618
Revises: 0df9f7fc524c
Create Date: 2026-03-24 10:12:38.850978

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f34d11135618'
down_revision: Union[str, None] = '0df9f7fc524c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_addons', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking_travelers', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('booking_travelers', 'family_member_id')
    op.create_index('ix_bookings_payment_status', 'bookings', ['payment_status'], unique=False)
    op.create_index('ix_bookings_user_status', 'bookings', ['user_id', 'status'], unique=False)
    op.create_index('ix_bookings_user_type', 'bookings', ['user_id', 'booking_type'], unique=False)
    op.alter_column('hotel_bookings', 'rooms_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotel_bookings', 'adults',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotel_bookings', 'children',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_hotel_bookings_hotel_id'), table_name='hotel_bookings')
    op.drop_index(op.f('ix_hotel_bookings_room_id'), table_name='hotel_bookings')
    op.drop_column('hotel_bookings', 'check_out_time')
    op.drop_column('hotel_bookings', 'check_in_time')
    op.alter_column('package_bookings', 'num_adults',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('package_bookings', 'num_children',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('package_bookings', 'addon_charges',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('vehicle_bookings', 'pickup_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('vehicle_bookings', 'return_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_vehicle_bookings_driver_id'), table_name='vehicle_bookings')
    op.drop_index(op.f('ix_vehicle_bookings_vehicle_id'), table_name='vehicle_bookings')
    op.drop_column('vehicle_bookings', 'actual_km')
    op.drop_column('vehicle_bookings', 'toll_charges')
    op.drop_column('vehicle_bookings', 'pickup_lng')
    op.drop_column('vehicle_bookings', 'pickup_lat')
    op.drop_column('vehicle_bookings', 'drop_lat')
    op.drop_column('vehicle_bookings', 'driver_allowance')
    op.drop_column('vehicle_bookings', 'drop_lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_bookings', sa.Column('drop_lng', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('vehicle_bookings', sa.Column('driver_allowance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('vehicle_bookings', sa.Column('drop_lat', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('vehicle_bookings', sa.Column('pickup_lat', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('vehicle_bookings', sa.Column('pickup_lng', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('vehicle_bookings', sa.Column('toll_charges', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('vehicle_bookings', sa.Column('actual_km', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_vehicle_bookings_vehicle_id'), 'vehicle_bookings', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_bookings_driver_id'), 'vehicle_bookings', ['driver_id'], unique=False)
    op.alter_column('vehicle_bookings', 'return_datetime',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('vehicle_bookings', 'pickup_datetime',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('package_bookings', 'addon_charges',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('package_bookings', 'num_children',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('package_bookings', 'num_adults',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('hotel_bookings', sa.Column('check_in_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('hotel_bookings', sa.Column('check_out_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_hotel_bookings_room_id'), 'hotel_bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_hotel_bookings_hotel_id'), 'hotel_bookings', ['hotel_id'], unique=False)
    op.alter_column('hotel_bookings', 'children',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hotel_bookings', 'adults',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hotel_bookings', 'rooms_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_bookings_user_type', table_name='bookings')
    op.drop_index('ix_bookings_user_status', table_name='bookings')
    op.drop_index('ix_bookings_payment_status', table_name='bookings')
    op.add_column('booking_travelers', sa.Column('family_member_id', sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column('booking_travelers', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('booking_addons', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
