"""add partners tables

Revision ID: f7e9ab2f9469
Revises: 18098d5c9e88
Create Date: 2026-03-17 14:08:26.002704

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f7e9ab2f9469'
down_revision: Union[str, None] = '18098d5c9e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('auto_accept', sa.Boolean(), nullable=False),
    sa.Column('unavailable_dates', sa.JSON(), nullable=True),
    sa.Column('notification_prefs', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_index(op.f('ix_partners_user_id'), 'partners', ['user_id'], unique=True)
    op.create_table('partner_bank_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('account_holder_name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_bank_details_id'), 'partner_bank_details', ['id'], unique=False)
    op.create_index(op.f('ix_partner_bank_details_partner_id'), 'partner_bank_details', ['partner_id'], unique=True)
    op.create_table('partner_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_documents_id'), 'partner_documents', ['id'], unique=False)
    op.create_index(op.f('ix_partner_documents_partner_id'), 'partner_documents', ['partner_id'], unique=False)
    op.create_table('partner_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_account', sa.String(length=20), nullable=True),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('transfer_ref', sa.String(length=100), nullable=True),
    sa.Column('transfer_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_payouts_id'), 'partner_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_partner_payouts_partner_id'), 'partner_payouts', ['partner_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('TRAVELER', 'PARTNER', 'GUIDE', 'ADMIN', name='userrole'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('TRAVELER', 'PARTNER', 'GUIDE', 'ADMIN', name='userrole'),
               server_default=sa.text("'TRAVELER'::userrole"),
               existing_nullable=False)
    op.drop_index(op.f('ix_partner_payouts_partner_id'), table_name='partner_payouts')
    op.drop_index(op.f('ix_partner_payouts_id'), table_name='partner_payouts')
    op.drop_table('partner_payouts')
    op.drop_index(op.f('ix_partner_documents_partner_id'), table_name='partner_documents')
    op.drop_index(op.f('ix_partner_documents_id'), table_name='partner_documents')
    op.drop_table('partner_documents')
    op.drop_index(op.f('ix_partner_bank_details_partner_id'), table_name='partner_bank_details')
    op.drop_index(op.f('ix_partner_bank_details_id'), table_name='partner_bank_details')
    op.drop_table('partner_bank_details')
    op.drop_index(op.f('ix_partners_user_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
